// Generated by CoffeeScript 1.10.0
(function() {
  window.Capybara || (window.Capybara = {});

  Capybara.Specs = (function() {
    Specs.prototype.generators = [];

    function Specs(options) {
      this.generators = [];
      this.tabURL = options.tabURL;
    }

    Specs.prototype.add = function(data) {
      switch (data.type) {
        case 'action':
          return this.generators.push(new Capybara.Generators.Action(data));
        case 'matcher':
          return this.generators.push(new Capybara.Generators.Matcher(data));
      }
    };

    Specs.prototype.setName = function(name) {
      return this.name = name;
    };

    Specs.prototype.generate = function() {
      var depth, generator, generatorScope, i, len, path, ref, ref1, scope, strings;
      ref = [0, [], null], depth = ref[0], strings = ref[1], scope = ref[2];
      strings.push("it '" + (this.name || "SHOULDDOSOMETHING") + "' do");
      depth++;
      path = this._parseURL(this.tabURL).pathname;
      strings.push(this._indent("visit('" + path + "')", depth));
      ref1 = this.generators;
      for (i = 0, len = ref1.length; i < len; i++) {
        generator = ref1[i];
        if (generator.isScoped()) {
          generatorScope = generator.scopeToPartials();
          if ((scope != null) && scope.join('') !== generatorScope.join('')) {
            strings.push(this._indent(_.last(generatorScope), --depth));
            scope = null;
          }
          if (!scope) {
            scope = generatorScope;
            strings.push(this._indent(_.first(generatorScope), depth++));
          }
        } else {
          if (scope != null) {
            strings.push(this._indent(_.last(scope), --depth));
            scope = null;
          }
        }
        strings.push(this._indent(generator.toString(), depth));
      }
      if (scope != null) {
        strings.push(this._indent(_.last(scope), --depth));
      }
      strings.push('end');
      return strings.join('\n');
    };

    Specs.prototype._indent = function(line, depth, indentation) {
      if (depth == null) {
        depth = 0;
      }
      if (indentation == null) {
        indentation = '  ';
      }
      while (depth-- > 0) {
        line = indentation + line;
      }
      return line;
    };

    Specs.prototype._parseURL = function(url) {
      var a;
      a = document.createElement('a');
      a.href = url;
      return a;
    };

    return Specs;

  })();

}).call(this);
